spring:
  application:
    name: courier-tracking
  datasource:
    url: jdbc:h2:mem:courierdb
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update